version: '2'

volumes:
  logs:
    driver: local

services:
  ppe2:
    container_name: ppe2
    #restart: always
    build:
      context: .
      args:
        - SERVER_NAME=ppe2.magicorp.fr
        - SERVER_ADMIN=support@magicorp.fr
    volumes:
      - ".:/var/www/html"
    labels:
      - "traefik.http.routers.ppe2.rule=Host(`ppe2.magicorp.fr`)"
      - traefik.http.routers.ppe2.middlewares=https-redirectscheme
      - "traefik.http.routers.ppe2-secure.rule=Host(`ppe2.magicorp.fr`)"
      - traefik.http.routers.ppe2-secure.tls=true
      - traefik.http.routers.ppe2-secure.tls.certresolver=sslresolver
    networks:
      - backend

networks:
  backend:
    external:
      name: backend
